### ISSUE TITLE
Rust-portaudio docs?

### ISSUE THREAD

**Issue by golddranks** [RustAudio/rust-portaudio#118]
Hi, is there any up-to-date documentation for rust-portaudio? If there is, it would be nice to have a link on the repo front page.

**Comment by mitchmindtree** [comment]
The documentation currently isn't hosted online, however you can read the docs by cloning the repo and running `cargo doc` and then dragging the generated `target/doc/portaudio/index.html` into your browser.

**Comment by wmedrano** [comment]
Have online documentation linked can be useful when shopping around libraries. Is there any reason this isn't done?

**Comment by donniebishop** [comment]
Is there a reason that the docs can't be hosted at docs.rs? It seems to attempt to generate docs on public crates, but for some reason the build fails: https://docs.rs/crate/portaudio/0.7.0/builds/28153

Could this be looked into? I agree with @wmedrano that having online documentation would definitely be helpful in seeing how the library is structured and organized before downloading it. Downloading and compiling the docs just to figure out that the library isn't what I'm looking for is a little less than pleasant.

**Comment by anlumo** [comment]
Building the docs requires the library portaudio itself for some reason, that's why it fails.

**Comment by wmedrano** [comment]
The README now links to `docs.rs` which is working
