### ISSUE TITLE
Vulnerable build script (MitM on network can make it execute arbitrary code)

### ISSUE THREAD

**Issue by magicgoose** [RustAudio/rust-portaudio#144]
Build script attempts to download portaudio code through plain http and without any signature checking (because there aren't any) and then run it.
https://github.com/RustAudio/rust-portaudio/blob/c776b83efc99984e54d6d1815d0a511ebe54ae05/build.rs#L62
https://github.com/RustAudio/rust-portaudio/blob/c776b83efc99984e54d6d1815d0a511ebe54ae05/build.rs#L75-L91

That's of course portaudio team's fault. But it's possible to download portaudio code from git as a safer alternative — https://app.assembla.com/spaces/portaudio/git/source.
I think, rust-portaudio should use this safer way to download code.

**Comment by alex** [comment]
This could also be addressed by verifying the hash of the tarball against one included in `build.rs`.

**Comment by tarcieri** [comment]
The tarball is only 1.5MB. The source code within could be vendored into the crate. Since it's available via git, it could be added to this project as a [git submodule](https://www.vogella.com/tutorials/GitSubmodules/article.html), which makes it easy to update and also easy to release new crates which already contain the source code and therefore don't have to hit the network to get it or worry about authenticating the retrieved artifact and unpacking it.

**Comment by barakugav** [comment]
This was solved by https://github.com/RustAudio/rust-portaudio/pull/190
Can we release a new versino? @mitchmindtree @jeremyletang @wmedrano

**Comment by mitchmindtree** [comment]
I don't have time for rust-portaudio these days I'm afraid, but I've just added the `github:rustaudio/rust-portaudio-maintainers` team as a crate owner, so a team member should be able to update it now

**Comment by wmedrano** [comment]
Done, this is live in `0.7.1`.

**Comment by wmedrano** [comment]
I didn't have permissions to push updates to `portaudio-sys` so forked into `portaudio-sys2`. Will try to contact @mvdnes for ownership.

**Comment by mvdnes** [comment]
Ha I didn't even remember the name portaudio. Funny seeing a 7 year old crate having >30 downloads per day. I fully agree this is a problem, so how can I help?

**Comment by mitchmindtree** [comment]
@mvdnes if you could, cd into `rust-portaudio-sys` and add the rustaudio portaudio maintainers team as a cargo owner:
```console
cargo owner --add github:RustAudio:rust-portaudio-maintainers
```

**Comment by wmedrano** [comment]
@mvdnes You may also be able to do it from the crates.io UI at https://crates.io/crates/portaudio-sys

**Comment by mvdnes** [comment]
I think there may be a problem with the name or the permissoins of the group. This is the response I get:

```
% cargo owner --add github:RustAudio:rust-portaudio-maintainers
    Updating crates.io index
error: failed to invite owners to crate `portaudio-sys` on registry at https://crates.io

Caused by:
  the remote server responded with an error (status 400 Bad Request): could not find the github team RustAudio/rust-portaudio-maintainers. Make sure that you have the right permissions in GitHub. See https://doc.rust-lang.org/cargo/reference/publishing.html#github-permissions
```

**Comment by wmedrano** [comment]
What about `cargo owner --add wmedrano`

**Comment by mvdnes** [comment]
> What about `cargo owner --add wmedrano`

That works, you now have an invite.
