### ISSUE TITLE
Looking for Maintainers

### ISSUE THREAD

**Issue by mitchmindtree** [RustAudio/rust-portaudio#177]
Hi all!

I no longer have the time or motivation to manage the rust-portaudio crate. These days, most of my efforts have been going into [CPAL](https://github.com/tomaka/cpal) - a pure-Rust alternative. As a result, I find it difficult to prioritise issues and PRs here.

If anyone would like to step in as the maintainer for the crate they would be more than welcome. I'd be happy to add them as an administrator to the RustAudio organisation if they are not already so.

**Comment by mcginty** [comment]
I volunteer to take ownership of this crate in the interim for maintenance purposes and bugfixes. If there's someone more excited about adding new features, happy to pass on ownership.

**Comment by Mec-iS** [comment]
I could consider taking ownership of `RustAudio/synth`, let me know.

**Comment by wmedrano** [comment]
I'd like to take ownership of `rust-portaudio` if the offer is still open.

**Comment by mitchmindtree** [comment]
Thanks all!

@mcginty Apologies for not replying here - I sent an invite a while back, hopefully you received it.

@Mec-iS I've been meaning to add a deprecation notice to `RustAudio/synth` for a while now - I think in retrospect it's quite convoluted for what it achieves, especially considering how much more concisely it could be written again now that `dasp` is around, but it was a fun way to learn Rust and if you'd like to hack on it I'd be happy to accept PRs :) 

@wmedrano thanks, it is indeed! I've just sent you an invite to the RustAudio portaudio team.
