### ISSUE TITLE
I am looking for an audio crate I can import to get various information about an audio file? 

### ISSUE THREAD

**Issue by Joe23232** [RustAudio/rust-portaudio#182]
I am looking for a high level audio crate library that allows me to easily get various information about an audio such as its loudness, tempo, current key/pitch etc? Can `rust-portaudio` do this?

**Comment by wmedrano** [comment]
No, portaudio is a library for IO. It can only play and record audio.

**Comment by wmedrano** [comment]
As for `information` do you mean from metadata or do you want a library that includes algorithms that can extract this from the signal?

**Comment by Joe23232** [comment]
>  library that includes algorithms that can extract this from the signal?

This one mate :)

**Comment by wmedrano** [comment]
Closing since this is not related to portaudio.

As far as algorithms, I'm not sure about rust. You may have better luck with Python or by researching the field and disregarding the programming language.
