### ISSUE TITLE
Can't get devices, but example works

### ISSUE THREAD

**Issue by Camaendir** [RustAudio/rust-portaudio#187]
I have used portaudio in a program of mine and it always fails to get the devices. Trying to access the default device or trying to access a device directly through its index results in a panic. Iterating over the devices just results in no devices being looped over. 

BUT, building and executing the example device.rs works, it prints a few errors, but then also prints the correct devices.

I've reinstalled portaudio a few times already.

What could be the problem for that?

**Comment by Camaendir** [comment]
I've tested this on a different machine now, and there it works as well.

I am trying to execute it on my Raspberry Pi and there the example works, but my code doesn't.

On another machine (my MacBook) the example as well as my code work.

**Comment by Camaendir** [comment]
I've reinstalled my OS and it fixed the problem.

**Comment by Nathy-bajo** [comment]
> I've reinstalled my OS and it fixed the problem.

Hi @Camaendir 

I am currently having this same issue, how did you fix yours?
Their example works and when I implement it on my mac it works but when I send it using `rsync` to my raspberrypi 4 it doesn't work still wondering why.
